version: '3'
services:
    akerclient:
        image: humbertosales/akerclient-x11
        privileged: true
        shm_size: 2G
        ports:
          - "3380:3389"
        environment:
          - DISPLAY=host.docker.internal:0.0
          - VPNRDPIP=<IP_DESKTOP_REMOTE_ACCESS>
        volumes:
          - /lib/modules:/lib/modules:ro
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ./home/:/root/
        